version: '3.8'

services:
  api01: &api
    image: braganathan38/rinhabackendspring-softplan:1.0
    hostname: api01
    networks:
      - default
    environment:
      POSTGRES_PASS: "1234"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "postgres"
    ports:
      - "8081:8080"
    depends_on:
      - postgres
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "200MB"

  api02:
    <<: *api
    hostname: api02
    environment:
      POSTGRES_PASS: "1234"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "postgres"
    ports:
      - "8082:8080"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    networks:
      - default
    deploy:
      resources:
        limits:
          cpus: "0.17"
          memory: "10MB"

  postgres:
    image: postgres:latest
    hostname: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
    ports:
      - "5432:5432"
    volumes:
      - ./script.sql:/docker-entrypoint-initdb.d/script.sql
    networks:
      - default
    deploy:
      resources:
        limits:
          cpus: "0.13"
          memory: "140MB"

networks:
  default:
    driver: bridge
